name: Build image
on: [push]
jobs:
  kaniko_build:
    name: kaniko build
    runs-on: ubuntu-latest
    container:
      image: gcr.io/kaniko-project/executor:debug
    steps:
      - uses: actions/checkout@v1
      - name: Create dockerconfig
        run: printf $FORMAT test > /kaniko/.docker/config.json
        env:
          FORMAT: '{"auths":{"https://index.docker.io/v1/":{"auth":"%s"}}}\n'
      - name: test format
        run: cat /kaniko/.docker/config.json
      - name: Build image
        run: /kaniko/executor
          --cache
          --destination paulshibanov/com:$GITHUB_SHA
