name: Lint
on: [push]
jobs:
  ng_lint:
    needs: [kaniko_build]
    name: ng lint
    runs-on: ubuntu-latest
    container:
      image: paulshibanov/com:$GITHUB_SHA
    steps:
      - name: Lint the code
        run: ng lint
